# project Information
site_name: John's Website
site_desciption: 'A project documentation website'
site_author: 'John Brereton'
site_url: 'http://jbrereton.com'
site_dir: '/var/www/html'

# Repository
repo_name: 
repo_url: https://github.com/johnBrereton
edit_uri: ''

# Copyright
copyright: 'Copyright &copy; 2018 - 2020 John Brereton'

# Page Tree
nav:
  - Home: index.md
  - FTC Team 12601: FTC.md
  - 3D Printing: 3d-Printing.md
  - Projects:
    - This Website: Projects/Website.md
    - CNC: Projects/CNC.md
    - Response to COVID-19: Projects/COVID-19.md
    - Raspberry Pi VPN: Projects/Pi-VPN.md

# Configuration
theme:
  name: material
  custom_dir: overrides
  language: en
  features:
    - instant
  palette:
    scheme: slate
    primary: blue
    accent: orange
  icon:
    logo: 'material/console'
  favicon: 'img/console.png'

# Extras
extra:
  disqus: 'johns-website'
  social:
    - icon: 'material/email'
      link: 'mailto:john@jbrereton.com'
    - icon: 'material/phone'
      link: 'tel:9085008621'
    - icon: 'material/github'
      link: 'https://github.com/johnBrereton'
    - icon: 'material/linkedin'
      link: 'https://www.linkedin.com/in/johnbrereton06/'
    - icon: 'material/instagram'
      link: 'https://www.instagram.com/johnBrereton06'
    - icon: 'material/facebook'
      link: 'https://facebook.com/johnBrereton06'
    - icon: 'material/twitter'
      link: 'https://twitter.com/johnBrereton06'

# Google Analytics
google_analytics:
  - 'UA-129700516-1'
  - 'auto'

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - meta

plugins:
  - search
  - git-revision-date-localized