# project Information
site_name: John's Website
site_desciption: 'A project documentation website'
site_author: 'John Brereton'
site_url: 'http://jbrereton.com'
site_dir: '/var/www/html'

# Repository
repo_name:
repo_url: https://github.com/johnBrereton

# Copyright
copyright: 'Copyright &copy; 2018 - 2020 John Brereton'

# Page Tree
nav:
  - Home: index.md
  - FTC Team 12601: FTC.md
  - 3D Printing: 3d-Printing.md
  - Projects:
    - This Website: Projects/Website.md
    - CNC: Projects/CNC.md
    - Response to COVID-19: Projects/COVID-19.md
    - Raspberry Pi VPN: Projects/Pi-VPN.md

# Configuration
theme:
  name: material
  palette:
    primary:
    secondary:
  font:
    text:
    code:
  icon:
    logo: terminal
    repo: fontawesome/brands/git-alt
  favicon: 'img\favicon.png'
  language: 'en'
  feature:
    tabs: false

# Customization
extra:
  disqus: 'johns-website'
  social:
    - type: 'github'
      link: 'https://github.com/johnBrereton'
    - type: 'envelope'
      link: 'mailto:john@jbrereton.com'

# Google Analytics
google_analytics:
  - 'UA-129700516-1'
  - 'auto'

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - meta
