# project Information
site_name: John's Website
site_desciption: A project documentation website
site_author: John Brereton
site_url: 'http://jbrereton.com'

# Repository
repo_name:
repo_url: https://github.com/jbrereton6/Website
# Page Tree
nav:
    - Home: index.md
    - FTC Team 12601: FTC.md
    - 3D Printing: 3d-Printing.md
    - Projects:
        - Raspberry Pi VPN: Projects/Pi-VPN.md
        - This Website: Projects/Website.md

# Configuration
theme:
  name: material
  palette:
    primary:
    secondary:
  font:
    text:
    code:
  logo:
    icon: 'computer'
  favicon: 'img\favicon.png'
  language: 'en'
  feature:
    tabs: false

# Customization
extra:
  disqus: 'johns-website'
  social:
    - type: 'github'
      link: 'https://github.com/jbrereton6'
    - type: 'envelope'
      link: 'mailto:john@jbrereton.com'

# Google Analytics
google_analytics:
  - 'UA-129700516-1'
  - 'auto'

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - meta
